version: '3.8'

services:
  web:
    build: .
    container_name: dsa-flask
    restart: always
    expose:
      - "5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=LilaDoodle0707!
      - MYSQL_DB=dsa_tracker
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: dsa-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LilaDoodle0707!
      MYSQL_DATABASE: dsa_tracker
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: dsa-nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web

volumes:
  mysql_data:
