name: CI/CD to Heroku

on:
  push:
    branches:
      - main  # Branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Replace with your test command, e.g. pytest or unittest discover
        python -m unittest discover

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        # Secret from Github
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Heroku app name
        heroku_app_name: "digital-skills-academy-tracker"
        # Heroku email
        heroku_email: "maddisonamy17@btinternet.com"
