# Name of workflow
name: Python Flask CI/CD

on:
  # Push the main branch
  push:
    branches: [ main ]
  # Push the main branch
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check repository code
    - uses: actions/checkout@v3
    # Set up Python env
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Run tests
      run: |
        # Replace with your test command (e.g., pytest)
        echo "Add your test command here"